"""
Navigation API endpoints — GenAI-powered multilingual route guidance.

Rate limiting: Stricter 10/min on GenAI endpoints to control Gemini API costs
during FIFA 2026 peak traffic while preventing abuse.
"""

from __future__ import annotations

import structlog
from fastapi import APIRouter, HTTPException, Request, status

from app.config import get_settings
from app.core.rate_limiter import limiter
from app.dependencies import Cache, CurrentUser, GenAINavigator
from app.domain.models.navigation import (
    LocalizedNavigationResponse,
    NavigationRequest,
    NavigationRoute,
    RouteStep,
)
from app.domain.models.crowd import CongestionLevel
from app.domain.services.graph_router import GraphRouter
from app.domain.repositories.stadium_repository import get_or_create_stadium_graph

logger = structlog.get_logger(__name__)
settings = get_settings()
router = APIRouter()


@router.post(
    "/route",
    response_model=LocalizedNavigationResponse,
    status_code=status.HTTP_200_OK,
    summary="Get GenAI-powered multilingual navigation route",
    description=(
        "Computes the optimal route from a fan's current zone to their destination, "
        "dynamically routing around congested areas. Returns a natural language "
        "description in the fan's preferred language, generated by Gemini 1.5 Pro. "
        "\n\nSupported languages: en, es, fr, pt, ar, zh."
    ),
)
@limiter.limit(settings.rate_limit_genai)
async def get_navigation_route(
    request: Request,
    payload: NavigationRequest,
    current_user: CurrentUser,
    cache: Cache,
    navigator: GenAINavigator,
) -> LocalizedNavigationResponse:
    """
    Compute and return a localized navigation route.

    Pipeline:
      1. Validate request (handled by Pydantic on payload).
      2. Load stadium graph (from cache or mock seeder).
      3. Fetch current crowd snapshot to get live congestion levels.
      4. Run Dijkstra routing with congestion-weighted edges.
      5. Call GenAI navigator for multilingual guidance.
      6. Return complete LocalizedNavigationResponse.

    Raises:
        404: Stadium not found or no crowd data yet.
        422: Invalid origin/destination zone IDs.
        503: If routing is impossible (e.g., all paths blocked).
    """
    # ── Load Stadium Graph ────────────────────────────────────────────────
    graph = get_or_create_stadium_graph(payload.stadium_id)

    # ── Fetch Live Congestion Data ────────────────────────────────────────
    congestion_levels: dict[str, str] = {}
    snapshot_raw = await cache.get(f"snapshot:{payload.stadium_id}")
    if snapshot_raw:
        from app.domain.models.crowd import StadiumCrowdSnapshot
        snapshot = StadiumCrowdSnapshot.model_validate_json(snapshot_raw)
        congestion_levels = {
            z.zone_id: z.congestion_level.value for z in snapshot.zones
        }
        crowded_zones = snapshot.critical_zone_ids
    else:
        crowded_zones = []
        logger.info(
            "no_crowd_snapshot_routing_uncongested",
            stadium_id=payload.stadium_id,
        )

    # ── Run Graph Router ─────────────────────────────────────────────────
    graph_router = GraphRouter(graph=graph)

    # Merge explicitly avoided zones with currently critical zones
    avoid_set = set(payload.avoid_zones) | set(crowded_zones)

    try:
        path = graph_router.find_route(
            origin_id=payload.origin_zone_id,
            destination_id=payload.destination_zone_id,
            congestion_levels=congestion_levels,
            require_accessible=payload.require_accessible_route,
            avoid_zones=avoid_set,
        )
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        )

    if path is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "No navigable path found. All routes may be blocked by congestion. "
                "Please wait for crowd conditions to improve or contact stadium staff."
            ),
        )

    # ── Build NavigationRoute from path ──────────────────────────────────
    total_distance, total_time = graph_router.compute_route_details(
        path, congestion_levels
    )

    steps: list[RouteStep] = []
    for i, zone_id in enumerate(path):
        node = graph.nodes.get(zone_id)
        instruction = _generate_step_instruction(
            zone_id=zone_id,
            step_index=i,
            is_last=(i == len(path) - 1),
            node_name=node.name if node else zone_id,
        )
        steps.append(
            RouteStep(
                step_index=i,
                zone_id=zone_id,
                instruction=instruction,
                estimated_seconds=(total_time / max(len(path) - 1, 1)) if i > 0 else 0.0,
                is_accessible_path=(node.is_accessible if node else True),
            )
        )

    route = NavigationRoute(
        origin_zone_id=payload.origin_zone_id,
        destination_zone_id=payload.destination_zone_id,
        stadium_id=payload.stadium_id,
        steps=steps,
        total_distance_meters=total_distance,
        total_time_seconds=total_time,
        avoids_zones=list(avoid_set),
        is_accessible_route=payload.require_accessible_route,
    )

    # ── GenAI Guidance ────────────────────────────────────────────────────
    response = await navigator.generate_navigation_guidance(
        route=route,
        language=payload.language,
        crowded_zones=crowded_zones,
    )

    logger.info(
        "navigation_route_generated",
        stadium_id=payload.stadium_id,
        origin=payload.origin_zone_id,
        destination=payload.destination_zone_id,
        language=payload.language.value,
        path_length=len(path),
        cache_hit=response.cache_hit,
        is_genai=response.is_genai_response,
    )

    return response


def _generate_step_instruction(
    zone_id: str,
    step_index: int,
    is_last: bool,
    node_name: str,
) -> str:
    """
    Generate a simple English navigation instruction for a route step.
    The GenAI service will localize and enrich these in the final response.
    """
    if step_index == 0:
        return f"Start at {node_name}"
    elif is_last:
        return f"Arrive at {node_name} — your destination"
    else:
        return f"Continue to {node_name}"
