"""
Domain models for crowd density and bottleneck data.

These Pydantic v2 models define the CORE BUSINESS ENTITIES — they are
independent of transport (HTTP) and storage (database) concerns, following
the Dependency Inversion principle. Schemas (in app/schemas/) handle the
HTTP layer transformation.

FIFA 2026 Scale consideration:
  A single stadium can have 500+ sensor zones. These models must be
  memory-efficient as they may be aggregated for 90,000 concurrent fans.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, Field, field_validator


class CongestionLevel(str, Enum):
    """
    Categorical congestion classification for fan-facing communication.
    String enum allows direct JSON serialization without value conversion.
    """
    LOW = "low"           # < 40% zone capacity
    MODERATE = "moderate" # 40–70% zone capacity
    HIGH = "high"         # 70–90% zone capacity
    CRITICAL = "critical" # > 90% zone capacity — triggers rerouting


class ZoneDensity(BaseModel):
    """
    Represents the instantaneous crowd density of a single stadium zone.

    A zone is a named area within a stadium (e.g., "Gate A", "Concourse 3",
    "Exit North-East"). Each zone maps to a graph node in the routing engine.
    """

    zone_id: str = Field(
        ...,
        description="Unique zone identifier within the stadium graph",
        pattern=r"^[A-Z0-9_-]{2,32}$",
        examples=["GATE_A", "CONCOURSE_3", "EXIT_NE"],
    )
    stadium_id: str = Field(
        ...,
        description="FIFA-assigned stadium code (e.g., 'METLIFE', 'ATT_STADIUM')",
        pattern=r"^[A-Z_]{3,20}$",
    )
    current_count: int = Field(
        ...,
        ge=0,
        description="Number of fans currently in this zone (from sensor fusion)",
    )
    capacity: int = Field(
        ...,
        gt=0,
        description="Maximum safe occupancy for this zone",
    )
    timestamp: datetime = Field(
        ...,
        description="UTC timestamp of this measurement",
    )

    @field_validator("current_count")
    @classmethod
    def validate_count_not_exceed_capacity_by_too_much(
        cls, v: int, info: object
    ) -> int:
        """
        Sensor readings can briefly exceed capacity (measurement lag).
        We allow up to 110% — anything beyond suggests a sensor malfunction.
        The validator fires here (not in service) to catch bad data at ingestion.
        """
        # We cannot access `capacity` here due to field validation order,
        # so capping is done in the service layer with a warning log.
        return v

    @property
    def occupancy_ratio(self) -> float:
        """Ratio of current count to capacity. O(1) computed property."""
        return self.current_count / self.capacity

    @property
    def congestion_level(self) -> CongestionLevel:
        """
        Derive categorical congestion level from occupancy ratio.
        Thresholds are configurable via FIFA Stadium Operations guidelines.
        """
        ratio = self.occupancy_ratio
        if ratio < 0.40:
            return CongestionLevel.LOW
        elif ratio < 0.70:
            return CongestionLevel.MODERATE
        elif ratio < 0.90:
            return CongestionLevel.HIGH
        else:
            return CongestionLevel.CRITICAL


class BottleneckPrediction(BaseModel):
    """
    Predicted future bottleneck for a specific zone.

    Generated by the crowd analytics service using graph-based propagation
    and historical match-event patterns (e.g., half-time surge at concessions).
    """

    zone_id: str
    stadium_id: str
    predicted_congestion: CongestionLevel
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Model confidence in the prediction (0.0–1.0)",
    )
    prediction_horizon_minutes: int = Field(
        ...,
        ge=1,
        le=60,
        description="How many minutes ahead this prediction is for",
    )
    predicted_at: datetime
    triggered_by: str = Field(
        ...,
        description="Event that triggered this prediction (e.g., 'HALF_TIME', 'GOAL')",
    )


class StadiumCrowdSnapshot(BaseModel):
    """
    Complete crowd state snapshot for an entire stadium at a point in time.
    Used as the primary payload for WebSocket real-time push and cached
    in Redis with a short TTL (30s by default).
    """

    stadium_id: str
    match_id: UUID
    snapshot_time: datetime
    zones: list[ZoneDensity]
    bottlenecks: list[BottleneckPrediction]
    overall_congestion: CongestionLevel

    @property
    def critical_zone_ids(self) -> list[str]:
        """
        Returns zone IDs at CRITICAL congestion level.
        Used by the navigation service to determine which zones to route around.
        Time complexity: O(n) where n = number of zones (typically ≤ 500).
        """
        return [
            z.zone_id
            for z in self.zones
            if z.congestion_level == CongestionLevel.CRITICAL
        ]
